/**
 * ShareExtension — in-app component that handles pending shares when the main
 * app resumes to the foreground.
 *
 * PRD §3.1.1 UI states:
 *   1. Loading — skeleton card placeholder (max 1.5s)
 *   2. Confirmation — thumbnail, title, category badge, "Saved to Oshi ✓"
 *   3. Category change — tap badge → category list bottom sheet
 *   4. Queued (offline) — "Queued — will save when back online"
 *
 * PRD §3.1.5: On foreground, check for pending shares and process them.
 * Show a non-blocking banner: "X saves queued — syncing now…"
 *
 * NOTE: This component renders in the MAIN app process, not in the iOS Share
 * Extension process. The native extension (generated by the config plugin)
 * handles the immediate share UI. This component handles:
 *   - Processing pending/queued shares when the app comes to foreground
 *   - Showing a syncing banner
 *   - Category re-assignment bottom sheet
 *
 * Uses theme values directly (not ThemeContext) since this may render before
 * ThemeProvider is mounted during cold start.
 */
import React, { useCallback, useEffect, useRef, useState } from 'react';
import {
  Animated,
  AppState,
  type AppStateStatus,
  FlatList,
  Modal,
  Pressable,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import * as Haptics from 'expo-haptics';

import { theme } from '../src/theme';
import {
  processPendingShares,
  getPendingShareCount,
  syncSessionToAppGroup,
  type ShareProcessResult,
} from '../src/services/shareExtension';
import { apiClient } from '../src/services/apiClient';

// ─────────────────────────────────────────────────────────────────────────────
// Constants — use light-mode theme values directly
// ─────────────────────────────────────────────────────────────────────────────
const { colors, borderRadius, spacing, shadows } = theme;

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface CategoryItem {
  id: string;
  name: string;
  emoji: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Syncing banner — "X saves queued — syncing now…"
// ─────────────────────────────────────────────────────────────────────────────

interface SyncBannerProps {
  pendingCount: number;
  result: ShareProcessResult | null;
  onDismiss: () => void;
}

function SyncBanner({
  pendingCount,
  result,
  onDismiss,
}: SyncBannerProps): React.JSX.Element {
  const opacity = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(opacity, {
      toValue: 1,
      duration: 250,
      useNativeDriver: true,
    }).start();
  }, [opacity]);

  useEffect(() => {
    if (result) {
      // Auto-dismiss after 3 seconds once processing is done
      const timer = setTimeout(() => {
        Animated.timing(opacity, {
          toValue: 0,
          duration: 200,
          useNativeDriver: true,
        }).start(() => onDismiss());
      }, 3_000);
      return () => clearTimeout(timer);
    }
    return undefined;
  }, [result, opacity, onDismiss]);

  let message: string;
  if (result) {
    if (result.failed === 0) {
      message = `${result.processed} save${result.processed === 1 ? '' : 's'} synced ✓`;
    } else {
      message = `${result.processed} synced, ${result.failed} still queued`;
    }
  } else {
    message = `${pendingCount} save${pendingCount === 1 ? '' : 's'} queued — syncing now…`;
  }

  return (
    <Animated.View
      style={[
        styles.banner,
        {
          backgroundColor: colors.primary,
          borderRadius: borderRadius.sm,
          opacity,
        },
      ]}
    >
      <Text style={styles.bannerText}>{message}</Text>
      <TouchableOpacity onPress={onDismiss} hitSlop={8}>
        <Text style={styles.bannerDismiss}>✕</Text>
      </TouchableOpacity>
    </Animated.View>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Category picker bottom sheet
// ─────────────────────────────────────────────────────────────────────────────

interface CategoryPickerProps {
  visible: boolean;
  categories: CategoryItem[];
  onSelect: (category: CategoryItem) => void;
  onClose: () => void;
}

function CategoryPicker({
  visible,
  categories,
  onSelect,
  onClose,
}: CategoryPickerProps): React.JSX.Element {
  const renderItem = useCallback(
    ({ item }: { item: CategoryItem }) => (
      <TouchableOpacity
        style={[styles.catRow, { paddingVertical: spacing.sm + 4, paddingHorizontal: spacing.md }]}
        onPress={() => onSelect(item)}
        activeOpacity={0.65}
      >
        <Text style={styles.catEmoji}>{item.emoji}</Text>
        <Text style={[styles.catName, { color: colors.textPrimary }]}>{item.name}</Text>
      </TouchableOpacity>
    ),
    [onSelect],
  );

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      <Pressable style={styles.overlay} onPress={onClose}>
        <View
          style={[
            styles.sheet,
            {
              backgroundColor: colors.surface,
              borderTopLeftRadius: borderRadius.lg,
              borderTopRightRadius: borderRadius.lg,
            },
          ]}
        >
          <View style={styles.handleRow}>
            <View style={[styles.handle, { backgroundColor: colors.border }]} />
          </View>
          <Text style={[styles.sheetTitle, { color: colors.textPrimary }]}>
            Change Category
          </Text>
          <FlatList
            data={categories}
            renderItem={renderItem}
            keyExtractor={(item) => item.id}
            style={{ maxHeight: 350 }}
          />
          <View style={{ height: spacing.xl }} />
        </View>
      </Pressable>
    </Modal>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// ShareExtensionHandler — top-level component
//
// Mount this inside App.tsx (or the root navigator). It listens for app
// foreground events and processes any pending shares automatically.
// ─────────────────────────────────────────────────────────────────────────────

export default function ShareExtensionHandler(): React.JSX.Element | null {
  const [showBanner, setShowBanner] = useState(false);
  const [pendingCount, setPendingCount] = useState(0);
  const [result, setResult] = useState<ShareProcessResult | null>(null);
  const [categories, setCategories] = useState<CategoryItem[]>([]);
  const [pickerVisible, setPickerVisible] = useState(false);
  const [lastProcessedSaveId, setLastProcessedSaveId] = useState<string | null>(null);

  const appStateRef = useRef<AppStateStatus>(AppState.currentState);

  // ── Check for pending shares on foreground ────────────────────────────

  const checkPendingShares = useCallback(async () => {
    try {
      // Sync session first so future extension uses have a fresh JWT
      await syncSessionToAppGroup();

      const count = await getPendingShareCount();
      if (count === 0) return;

      setPendingCount(count);
      setResult(null);
      setShowBanner(true);

      const processResult = await processPendingShares();
      setResult(processResult);

      if (processResult.processed > 0) {
        await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      }
    } catch {
      setShowBanner(false);
    }
  }, []);

  useEffect(() => {
    // Check on mount (cold start after a share)
    void checkPendingShares();

    // Listen for foreground transitions
    const subscription = AppState.addEventListener('change', (nextState) => {
      if (
        appStateRef.current.match(/inactive|background/) &&
        nextState === 'active'
      ) {
        void checkPendingShares();
      }
      appStateRef.current = nextState;
    });

    return () => subscription.remove();
  }, [checkPendingShares]);

  // ── Fetch categories for the picker ───────────────────────────────────

  useEffect(() => {
    async function loadCategories(): Promise<void> {
      try {
        const res = await apiClient.get<{ categories: CategoryItem[] }>('/categories');
        setCategories(
          res.data.categories.map((c) => ({
            id: c.id,
            name: c.name,
            emoji: (c as CategoryItem & { emoji?: string }).emoji ?? '📌',
          })),
        );
      } catch {
        // Categories will just be empty — picker won't open
      }
    }
    void loadCategories();
  }, []);

  // ── Category change handler ───────────────────────────────────────────

  async function handleCategoryChange(category: CategoryItem): Promise<void> {
    setPickerVisible(false);
    if (!lastProcessedSaveId) return;
    try {
      await apiClient.patch(`/saves/${lastProcessedSaveId}`, {
        category_id: category.id,
      });
    } catch {
      // Non-fatal — category wasn't changed
    }
  }

  // ── Render ────────────────────────────────────────────────────────────

  if (!showBanner) return null;

  return (
    <>
      <SyncBanner
        pendingCount={pendingCount}
        result={result}
        onDismiss={() => setShowBanner(false)}
      />
      <CategoryPicker
        visible={pickerVisible}
        categories={categories}
        onSelect={(cat) => void handleCategoryChange(cat)}
        onClose={() => setPickerVisible(false)}
      />
    </>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Styles
// ─────────────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  // ── Banner ────────────────────────────────────────────────────────────────
  banner: {
    position: 'absolute',
    top: 60,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    zIndex: 999,
    ...shadows.card,
    elevation: 10,
  },
  bannerText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
    marginRight: 12,
  },
  bannerDismiss: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 16,
    fontWeight: '600',
  },

  // ── Category picker ───────────────────────────────────────────────────────
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  sheet: {
    paddingTop: 8,
  },
  handleRow: {
    alignItems: 'center',
    paddingBottom: 8,
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: '700',
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  catRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  catEmoji: {
    fontSize: 20,
  },
  catName: {
    fontSize: 16,
    fontWeight: '500',
  },
});
